version: '3'
services:


 broker:
   image: eclipse-mosquitto:1.6
   container_name: mqtt_broker
   restart: always
   volumes:
    - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf

 sensoren:
  build: ./Sensor
  container_name: sensor
  working_dir: /Sensor
  command: "gradle run --quiet"
  environment:
  - SERVER=broker
  - DESTINATION=zentrale
  depends_on: 
    - broker
  
 zentrale:
  build: ./Zentrale
  container_name: zentrale
  ports:
  - 4711:4711/udp
  - 8000:8000/tcp
  - 1885:1885/tcp
  working_dir: /Zentrale
  command: "gradle run --quiet"
  environment:
   - SERVER=broker
  depends_on:
    - broker
  
 externerclient:
   build: ./externerClient
   container_name: externerclient
   ports:
   - 9090:9090/tcp
   working_dir: /externerClient
   command: "gradle run --quiet" 
   environment:
   - SERVER=zentrale
   depends_on: 
   - zentrale
